version: "3"
services:

  oj-redis:
    image: redis:4.0-alpine
    container_name: oj-redis
    restart: always
    volumes:
      - $PWD/data/redis:/data
  
  oj-postgres:
    image: postgres:10-alpine
    container_name: oj-postgres
    restart: always
    volumes:
      - $PWD/data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=onlinejudge
      - POSTGRES_USER=onlinejudge
      - POSTGRES_PASSWORD=onlinejudge

#  oj-forum:
#    image: php:7.4-fpm-alpine
#    container_name: oj-forum
#    restart: always
#    volumes:
#      - $PWD/data/forum:/forum
#    environment:
#      - STATIC_CDN_HOST=
    
  judge-server:
    image: registry.cn-qingdao.aliyuncs.com/wenjian_oj/judge_server
    container_name: judge-server
    restart: always
    read_only: true
    cap_drop:
      - SETPCAP
      - MKNOD
      - NET_BIND_SERVICE
      - SYS_CHROOT
      - SETFCAP
      - FSETID
    tmpfs:
      - /tmp
    volumes:
      - $PWD/data/backend/test_case:/test_case:ro
      - $PWD/data/judge_server/log:/log
      - $PWD/data/judge_server/run:/judger
    environment:
      - SERVICE_URL=http://judge-server:8080
      - BACKEND_URL=http://oj-backend:8000/api/judge_server_heartbeat/
      - TOKEN=your_secure_token_here
  
  oj-backend:
    image: registry.cn-qingdao.aliyuncs.com/wenjian_oj/backend
    container_name: oj-backend
    restart: always
    depends_on:
      - oj-redis
      - oj-postgres
      - judge-server
#      - oj-forum
    volumes:
      - $PWD/data/backend:/data
      - $PWD/data/forum:/forum
    environment:
      - POSTGRES_DB=onlinejudge
      - POSTGRES_USER=onlinejudge
      - POSTGRES_PASSWORD=onlinejudge
      - JUDGE_SERVER_TOKEN=your_secure_token_here
    ports:
      - "0.0.0.0:80:8000"
      - "0.0.0.0:443:1443"
